### ISSUE TITLE
Only get PHONE_REGISTRATION_ERROR, anybody knows whats up?

### ISSUE THREAD

**Issue by Asdfgasdfg312** [nborrmann/jodel_api#67] opened 2018-03-01 19:15 UTC
I only get PHONE_REGISTRATION_ERROR when i try to verify an account, no matter what I try, I've tried with proxy, I tried with python 2.7 and 3. Reinstalled the jodel api, currently using version jodel api version 1.2.10. But always the same error.

The biggest suspicion i have is that jodel_api seems to be targeting version 4.77.4 while jodel has released 4.78.1, but other people seems to get it to work so i guess its something on my side? I don't have any fancy code at all, just import, create account then try to verify it. But still same issue. I get as far as to create the account then i get the registration error. Anyone had the same problems?

**Comment by nborrmann** [comment] 2018-03-02 12:58
Duplicate of #61

**Closed by nborrmann** 2018-03-02 12:58 UTC
